### ISSUE TITLE
关于网络配置的一些问题

### ISSUE THREAD

**Issue by naibaicai** [CaiJi-ikun/DG_LAB#1]
up做的mod太棒了！不过关于连接有一点小问题。
在内网穿透的情况下（本人使用的radminlan），mod会优先使用radmin的ip，也就是说用郊狼的二维码扫描上之后会一直显示正在连接中，因为此时mod并没有运行在自己家内的局域网。

临时解决方法，关闭内网穿透软件，在网络适配器中禁用该网络，确保只有一个和手机在同一个局域网内的网络。

需要改进的解决办法：up可以在mod界面中添加一个自定义ip地址的框，可以参考b站另一位up做的mc郊狼联动（https://www.bilibili.com/video/BV1Af421i7fh/?spm_id_from=333.337.search-card.all.click）中的网络配置选项

另up可以选择把教程在网络连接方面稍微做详细点，感觉很多人不知道怎么连接到郊狼qwq，感谢up了

ps:第一次用github的issues，大概是这样用的吧，如有错误还请大佬指出

**Comment by CaiJi-ikun** [comment]
新版本出了可以自定义ip了:)
